CREATE TABLE CAIXA
(
    DATA            DATETIME,
    SALDO_INICIAL   DECIMAL(10,2),
    SALDO_FINAL     DECIMAL(10,2)
)

 

INSERT INTO CAIXA VALUES (cast(GETDATE() as date), 100, 100)

 

CREATE TABLE VENDAS
(
    DATA    DATETIME,
    CODIGO  INT,
    VALOR   DECIMAL(10,2)
)
go

 

CREATE TRIGGER TGR_VENDAS_AI
ON VENDAS
FOR INSERT
AS
BEGIN
    DECLARE
    @VALOR  DECIMAL(10,2),
    @DATA   DATETIME
 
    SELECT @DATA = DATA, @VALOR = VALOR FROM INSERTED
 
    UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL + @VALOR
    WHERE DATA = @DATA
END
go
 
INSERT INTO VENDAS VALUES (cast(GETDATE() as date), 999888, 10)
INSERT INTO VENDAS VALUES (cast(GETDATE() as date), 999823, 60)

 

select * from VENDAS
select * from CAIXA

go

CREATE TRIGGER TGR_VENDAS_AD
ON VENDAS
for DELETE
AS
BEGIN
    DECLARE
    @VALOR  DECIMAL(10,2),
    @DATA   DATETIME

    SELECT @DATA = DATA, @VALOR = VALOR FROM DELETED

    UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL - @VALOR
    WHERE DATA = @DATA
END
go

delete from vendas where CODIGO = 999823

go
CREATE TRIGGER TGR_VENDAS_AU
ON VENDAS
FOR UPDATE
AS
BEGIN
    DECLARE
    @VALOR_ANTIGO  DECIMAL(10,2),
    @VALOR_NOVO  DECIMAL(10,2),
    @DATA   DATETIME

 

    SELECT @DATA = DATA, @VALOR_ANTIGO = VALOR FROM DELETED

 

    SELECT @VALOR_NOVO = VALOR FROM INSERTED

 

    UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL - @VALOR_ANTIGO + @VALOR_NOVO
    WHERE DATA = @DATA 
END
go
 
select * from CAIXA
select * from VENDAS

update VENDAS set VALOR = 70 where CODIGO = 999888
INSERT INTO VENDAS VALUES (cast(GETDATE() as date), 999823, 60)
update VENDAS set VALOR = 50 where CODIGO = 999823


